export const {
  REACT_APP_ENV,
  REACT_APP_API_BASE_URL,
  NODE_ENV,
  PUBLIC_URL,
  REACT_APP_LINKS__CALL_ADT,
  REACT_APP_LINKS__TERMS_OF_SERVICE,
  REACT_APP_LINKS__FAQ,
  REACT_APP_LINKS__PRIVACY_POLICY,
  REACT_APP_LINKS__MYADT,
} = process.env;
export const API_BASE_URL = REACT_APP_API_BASE_URL;
